# https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html?from=jetbrains.org#earlier-versions
sinceBuild=231
intellijIdeaCommunityVersion=2023.1

platformPlugins=
platformBundledPlugins=

pluginId=com.arangodb.intellij.aql
pluginName=AQL (ArangoDB Query Language)
pluginVersion=1.1.0
pluginDescription=<p>AQL <a href="https://www.arangodb.com/"> ArangoDB</a> Query Language support</p>\
                  <ul>\
                    <li>Syntax highlighting</li>\
                    <li>Find usages</li>\
                    <li>Refactorings</li>\
                    <li>Quick docs</li>\
                    <li>Go to usages</li>\
                    <li>Execute queries</li>\
                  </ul>

pluginVendorName=machak
pluginVendorEmail=marijan@apache.org
pluginVendorUrl=https://www.machak.com

changeNotes=<ul>\
              <li><strong>1.0.8</strong></li>\
              <li>add WINDOW keyword</li>\
              <li>add remaining v3.7 and v3.8 functions:</li>\
              <li>IPV4_FROM_NUMBER, REPLACE_NTH, NGRAM_MATCH, NGRAM_SIMILARITY</li>\
              <li>NGRAM_POSITIONAL_SIMILARITY, DATE_UTCTOLOCAL, DATE_LOCALTOUTC</li>\
              <li>BIT_AND, BIT_OR, BIT_XOR,BIT_NEGATE, BIT_TEST, BIT_POPCOUNT, BIT_SHIFT_LEFT</li>\
              <li>BIT_SHIFT_RIGHT, BIT_CONSTRUCT, BIT_DECONSTRUCT, BIT_TO_STRING, BIT_FROM_STRING</li>\
              <li>GEO_IN_RANGE, DATE_TIMEZONE, DATE_TIMEZONES</li>\
              <li>fix syntax highlighting (+ function type "relaxing")</li>\
            <ul>\
              <p>1.0.7  SSL connection support, 3.8.x database support, bugfixes</p>\
              <p>1.0.6  </p>\
              <p>1.0.5 bug fixes, add new analyzers, keywords and functions(grammar/autocompletee), add function parameter hints (CTRL+P), add live template support</p>\
              <p>1.0.4 Add 2019.2+ support, use password manager to store passwords</p>\
              <p>1.0.3 bug fixes, create SpringData Repository interface intention</p>\
              <p>1.0.2 bug fixes</p>\
              <p>1.0.1 bug fixes (syntax highlighting, documentation)</p>\
              <p>1.0.0 initial release (syntax highlighting, autocompletion, refactorings, spring data query language injection)

